### ISSUE TITLE
Import RDS Code

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-boto3-plugin#1]

**Comment by EarthmanT** [comment]
These are just issues to set the format for the plugin - no functional comments.

*general notes:*

- [ ] add cloudify-aws-rds-plugin project content
- [ ] rename package from cloudify_aws to cloudify_boto3 + refactor import paths
- [ ] rename the serverless package to lambda_serverless
- [ ] add Gigaspaces copyright headers to all python files.
- [ ] maintain flake8 validation
- [ ] consider to change the constant REL_CONTAINED_IN to CONTAINED_IN_REL since it is more readable.
- [ ] lots of duplicated code in xyz/connection.py, xyz/utils.py, etc.
- [ ] 



*plugin.yaml*

- [ ] remove tosca_definitions_version
- [ ] rename plugin name from pkg to something else, e.g. awssdk
- [ ] rename plugin definition package_name to cloudify-boto3-plugin
- [ ] change plugin source to new incubator URL
- [ ] refactor type name space from cloudify.aws.rds.nodes/relationships.X to cloudify.aws.nodes/relationships.rds.X
- [ ] don't use anchors in plugin.yaml - duplicate the YAML, this must be readable.
- [ ] remove Base_config and BaseInterface_config dsl_definitions
- [ ] For each node type, define a data type for the resource_config, example:
```yaml
  cloudify.aws.nodes.rds.Instance:
    derived_from: cloudify.nodes.Root
    properties:
      use_external_resource:
        type: boolean
        # etc
      resource_id:
        type: string
        # etc
      client_config:
        type: cloudify.datatypes.aws.Config # or ...aws.rds.Config if it is different.
        # etc
      resource_config:
        type: cloudify.datatypes.aws.RDSInstance
        # etc
```
- [ ] force_operation should not be a dictionary in properties, only an input to the operation
- [ ] runtime_properties should not be a dictionary in properties, only an input to the operation
- [ ] aws_resource_id should not be a dictionary in properties, only an input to the operation 
- [ ] add documentation links to all node types like in line 89.
