### ISSUE TITLE
awssdk.cloudify_boto3.rds.resources.parameter_group.configure empty list fails validation 

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-boto3-plugin#15]
The blueprint input was like this:

```yaml
  ParameterGroup1:
    type: cloudify.nodes.aws.rds.ParameterGroup
    properties:
      resource_id: ParameterGroup1
      resource_config:
        kwargs:
          DBParameterGroupName: ParameterGroup1
          DBParameterGroupFamily: mysql5.6
          Description: Parameter Group 1
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.aws.rds.parameter_group.connected_to
      target: parameter_1
```

Error is:
```shell
Task failed 'cloudify_boto3.rds.resources.parameter_group.configure' -> Parameter validation failed:
Missing required parameter in input: "Parameters"
Unknown parameter in input: "DBParameterGroupFamily", must be one of: DBParameterGroupName, Parameters
Unknown parameter in input: "Description", must be one of: DBParameterGroupName, Parameters
```

There are several solutions. I think that if resource_config is None, there is no reason [here](https://github.com/cloudify-incubator/cloudify-boto3-plugin/blob/dev/cloudify_boto3/rds/resources/parameter_group.py#L109) to run the configure operation.
