### ISSUE TITLE
RDS

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-boto3-plugin#2]
- [x] AWS::RDS::DBInstance
- [x] AWS::RDS::OptionGroup
- [x] AWS::RDS::DBSubnetGroup
- [x] AWS::RDS::DBParameterGroup
- [ ] Unit tests

**Comment by 01000101** [comment]
The core types are done and are showcased in the `examples/rds-feature-demo/blueprint.yaml` blueprint. There's currently no "proper" integration with IAM yet but it can already be done using attributes in the following way:

```
  rds_mysql_instance:
    type: cloudify.nodes.aws.rds.Instance
    properties:
      resource_id: devdbinstance
      client_config: *client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              DBInstanceClass: db.t2.small
              Engine: mysql
              EngineVersion: 5.7.16
              # Attach IAM roles
              MonitoringRoleArn: { get_attribute: [my_monitoring_iam_role, aws_resource_arn] }
              DomainIAMRoleName: { get_attribute: [my_domain_iam_role, aws_resource_arn] }
```

Please review.
